### ISSUE TITLE
Unexpected keyword argument in subprocess.run()

### ISSUE THREAD

**Issue by guyfawcus** [azeam/camset#1]
### The issue
I just installed camset and received version 0.0.3,  ̶n̶o̶t̶ ̶s̶u̶r̶e̶ ̶w̶h̶y̶ ̶I̶ ̶d̶i̶d̶n̶'̶t̶ ̶g̶e̶t̶ ̶0̶.̶0̶.̶5̶** but that's irrelevant as this would still effect the latest version. After running, I got this error:

```
Traceback (most recent call last):
  File "/home/me/.local/bin/camset", line 11, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.6/site-packages/camset/camset.py", line 228, in main
    check_devices()
  File "/home/me/.local/lib/python3.6/site-packages/camset/camset.py", line 197, in check_devices
    devices = subprocess.run(['v4l2-ctl', '--list-devices'], check=True, text=True, stdout=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```

### The cause
The reason for the error was because I was running Python 3.6.9 (so close!) and according to the [subprocess docs](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module):

> Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter.

### The fix
Either upgrading to Python 3.7+ or doing a find-and-replace on _camset.py_ and changing `text=True` to `universal_newlines=True`

### Going forward
It's stated in [the package](https://pypi.org/project/camset/) that it requires **Python >=3.7** so I guess this isn't really a bug, but a small change* to using `universal_newlines` would allow a load of other people to use this software without running into this.

\* I can't believe I'm suggesting this by the way! I'm usually the one shouting _"out with the old, in with the new"_

\** Before 935e75001ce49fce57614601442c782bd9288d63 (version 0.0.4) any Python 3 version was "supported" so I was given the latest version that Pip reckoned I could use

**Comment by guyfawcus** [comment]
Should mention - otherwise, loving this application! I've been after something like it for aages. Good work! :+1:

**Comment by azeam** [comment]
Thanks for the report! Indeed the 3.7 version requirement is because of this, never looked in to the details though, universal_newlines does definitely seem like a better solution than restricting it to 3.7. Not sure what current requirements are but will set it to 3.0 for now.

**Comment by guyfawcus** [comment]
Thank you!  I wish there was an easier way to check a script against multiple versions without having to use [Travis](https://travis-ci.org/) or manually spin up a load of venvs, even if it just checked the syntax.
