### ISSUE TITLE
Settings not stored permanently 

### ISSUE THREAD

**Issue by DavidEGx** [azeam/camset#12]
Configuration is not stored permanently so whenever I have to use the camera I need to open camset and change options.

Could you change Camset so settings are stored forever? Maybe adding a "Store permanently" button.

Steps to reproduce:
1. Open Camset
2. Change settings
3. Close Camset
4. Unplug camera (or power off in case of built-in webcam)
5. Plug camera (or power on)
6. Open Camset

Settings went to default :'(

---

Thanks for the app!

**Comment by azeam** [comment]
Sorry, I totally forgot about this issue. Will put it on the todo-list and try to find some time to look into it!

**Comment by titouan73** [comment]
Thanks I'll try to make the load operation persistant :100:

**Comment by titouan73** [comment]
The fact is that, it's pretty hard to set params persistently (I mean even after reboot and/or unplug). The only things I get working is create a deamon that run  a while infinite loop which execute v4l2-ctl commands every seconds. That's very ugly I admit.

**Comment by titouan73** [comment]
It work like a charm, moreover Camset doesn't take CPU usage so it can be run as a background application without problem, thanks again for your help and your time !
