### ISSUE TITLE
Exposure (Absolute) slide bar: just display 0-20% range

### ISSUE THREAD

**Issue by rlemosor** [azeam/camset#14]
Love the GUI, just a tweak/enhancement request: could we have the exposure (Absolute) slide bar be confined to values between 0 and 20%? I just need to tweak it throughout the day between 3 and 8%, but can't get fine grained control with the current 0 to 100% scale. Maybe there could be an additional option if folks really need more than 20% exposure. Thanks!

**Comment by azeam** [comment]
Thanks for the suggestion! See if this helps (updated version 0.0.13 available at pip), it is still 0-100% but it should be easier to set the values more precisely.

**Comment by rlemosor** [comment]
Thanks, look forward to try it out! Do you know if it would it be available via dnf? I originally installed it via `sudo dnf install gtk-v4l` based on this guidance:
https://askbot.fedoraproject.org/en/question/72340/any-program-in-fedora-that-can-edit-webcam-settings/

I'm on Fedora 33.

**Comment by azeam** [comment]
> Thanks, look forward to try it out! Do you know if it would it be available via dnf? I originally installed it via `sudo dnf install gtk-v4l` based on this guidance:
> https://askbot.fedoraproject.org/en/question/72340/any-program-in-fedora-that-can-edit-webcam-settings/
> 
> I'm on Fedora 33.

Looks very similar but that is a totally different application ;) It is not available via dnf to my knowledge.

**Comment by rlemosor** [comment]
Ah, sorry about that, I did have some trouble finding the right repo for the app I'm having on my workstation (screenshot attached). Thanks anyway! 
![Uploading Screenshot from 2021-05-27 10-13-21.png…]()
