### ISSUE TITLE
wrong camset.desktop

### ISSUE THREAD

**Issue by christofarn** [azeam/camset#15]
Starting camset via program's menu in linux fails.
This is due to: camset is installed in /home/[[myuser]]/.local/bin/camset. But the program starting file "camset.desktop" has in line 4 something like
Exec=/usr/bin/camset

Changing that line 4 to
Exec=.local/bin/camset
helps.

**Comment by azeam** [comment]
camset.desktop only contains the line `Exec=camset`, which will make it look for the executable under your $PATH environment variable. Unfortunately the default pip install directory (`~/.local/bin`) is not in the default binary path on many (Debian-based) distros, but adding it to your $PATH as [described](https://github.com/azeam/camset/blob/master/README.md) under "Installation" should solve that issue.

**Comment by christofarn** [comment]
Thank you!
As camset is now a very important program when zoom.us and similar has becoming more important, I'd wish we had a installation routine that would help not so advanced linux users. A recipe how to set up the path environment permanently (!) would be helpful - or a installation routine that could place a symlink in a folder, that is typically part of the path environment, of possible. - If any of those would be possible. I helped myself as I'm familiar with .desktop-files, but not with the path environment. - And I like camset - thanks so much for providing it!

**Comment by azeam** [comment]
Updated the readme with some more detailed instructions, there are several possible combinations depending on how pip and the distro are set up, so I don't think it's a good idea to try to sort it programmatically, but I believe this should be the most common solution. I also _think_ this has been changed (`~/.local/bin` is in the default PATH) on more recent (20.04+ ?) Ubuntu versions but I'm not sure.

**Comment by christofarn** [comment]
Thanks a lot! - I use debian, so I can't verify what is in the default PATH in ubuntu. Camset is great! :-)
