### ISSUE TITLE
Stuck at installing build dependencies

### ISSUE THREAD

**Issue by fabiocyro** [azeam/camset#21]
Hello!

So, after many researching I came up to camset that will solve my problems for sure. But as the title says, it is getting stuck at "Installing building dependencies"

I have to tell you also that I am try to install on a Raspberry Pi 3b+. Maybe that is the reason?

Is there any other way? I think the problem is with opencv, but I already have a version installed. Can I ignore on the installation?

Sorry if I asked something stupid, I'm unexperienced on this.

**Comment by azeam** [comment]
Haven't tried to install it on a raspberry pi and don't have one accessible at the very moment, but all dependencies should be available for ARM/RPi afaik. What distro are you running? What error messages do you get?

**Comment by fabiocyro** [comment]
> Haven't tried to install it on a raspberry pi and don't have one accessible at the very moment, but all dependencies should be available for ARM/RPi afaik. What distro are you running? What error messages do you get?

Hello @azeam thanks for the quick answer.

So, I'm running ubuntu 20.04 on it with ROS Noetic for working a turtlebot3 (to be very precise), and there is no error honestly, just the installer that seems stuck. 

That "/" that keeps spining once you have the "Installing build dependencies"... it stops spinning (or super slow i guess), like it is stuck. I left for more than one hours and still stuck. So maybe i should just let it?

Like I told u, i already have opencv, it was installed when i installed a package Autorace and this process took me around 3 hours.

So maybe i should just let it?

**Comment by fabiocyro** [comment]
Hello just for an update about it: As I imagine I just had to wait, it took around 6 hours but now there's another issue:

```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/camset", line 5, in <module>
    from camset.camset import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/camset/camset.py", line 181, in <module>
    win = Window()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/camset/camset.py", line 15, in __init__
    Gtk.Window.__init__(self, title="Camset")
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 520, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
```

I'm feeling I'm getting close make it work though, but I have no idea on how to fix this

**Comment by fabiocyro** [comment]
Hello just coming back for some feedback and after reading a lot I came to the conclusion that it doesn't work for me for many reasons:

First, I am running a Ubuntu server, so no GUI and no packages to run a GUI.

Second is that even after installing one I'm getting the following error: 

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/camset/camset.py", line 55, in on_btn_showcam_toggled
    camwin.init_camera_feed(helpers.get_video_resolution(self))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/camset/helpers.py", line 18, in get_video_resolution
    vfeedheight = resolution.split("x", 1)[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/camset/camset.py", line 76, in on_device_changed
    self.clear_and_rebuild()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/camset/camset.py", line 46, in clear_and_rebuild
    self.read_capabilites()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/camset/camset.py", line 149, in read_capabilites
    value = int(line.split(": ", 1)[0]) # get value from text because index is not (always) same as value
ValueError: invalid literal for int() with base 10: 'Codec Controls'
```

I understabd what the error says but I don't know how to fix it haha
