### ISSUE TITLE
camset or Camtest?

### ISSUE THREAD

**Issue by guyfawcus** [azeam/camset#4]
What's the name of this application? :stuck_out_tongue_winking_eye: 

![camset-name](https://user-images.githubusercontent.com/1242894/80948995-0fcac780-8deb-11ea-880a-fa188211406a.png)

Guessing _Camtest_ was a placeholder name when you started developing this?

https://github.com/azeam/camset/blob/022cc73c1e79e6f6c7b314669430fc14a9114073/camset/camset.py#L218-L222

**Comment by azeam** [comment]
Oups, will fix! :) (Not only is "test" a too often used word and thoroughly implemented in muscle-memory, but also the same letters as "set", I've actually noted that I've written "camtest" when meaning to write "camset" before as well).

**Comment by guyfawcus** [comment]
Haha, been there before!
