### ISSUE TITLE
Add flag to start camset with camera feed off by default

### ISSUE THREAD

**Issue by liquidat** [azeam/camset#6]
I use camset to change values of my camera _during_ running video conferences, like changing white balance to manual, etc.

However, when I open camset (and change to my camera) I get an error because the device is already in use since a video stream is running:
![Screenshot from 2020-11-24 16-00-06](https://user-images.githubusercontent.com/1998084/100111243-2f503d00-2e6e-11eb-9cbb-7d6d7c7f0d4d.png)
If I confirm the dialog, I am able to change the values as needed, adjusting my currently running feed.

It would be great to have a way to start camset with the video streams off by default, like `--no-camera-feed-by-default` or something, so that I don't have to confirm the dialog all the time.
Or, even better, it would be nice if camset would just show a passive warning, without me needing to confirm that.

**Comment by azeam** [comment]
Thanks for the report. I've made an attempt at a less obtrusive error message, while keeping the default behavior of starting the feed when the application starts, does this work for you? (The changes have been pushed to pip).

**Comment by liquidat** [comment]
@azeam Thanks for the quick reply and the quick fix - that is awesome! And yes, it is way less intrusive now, and really works for me:
![Screenshot from 2020-11-25 13-19-11](https://user-images.githubusercontent.com/1998084/100227101-e4dbc880-2f20-11eb-8f92-d22f631cadee.png)
Thank you so much!
